[project]
name = "posit-conf-2025-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.64.0",
    "chatlas>=0.11.0",
    "dotenv>=0.9.9",
    "openai>=1.102.0",
    "pyhere>=1.0.3",
    "shiny>=1.4.0",
]
